// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATKqmrJhAQlmM25w-yyr3jIpOyTPjr1pU',
    appId: '1:487529716430:web:a2a07d1f2f9b89351d8e9f',
    messagingSenderId: '487529716430',
    projectId: 'barrelsnap-8b4a6',
    authDomain: 'barrelsnap-8b4a6.firebaseapp.com',
    storageBucket: 'barrelsnap-8b4a6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMksQwdj3z2j26wwP4fAqV2OUWsOn75w8',
    appId: '1:487529716430:android:9e1a632e77784e081d8e9f',
    messagingSenderId: '487529716430',
    projectId: 'barrelsnap-8b4a6',
    storageBucket: 'barrelsnap-8b4a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4XzQ8Hud8eFnSjIvJDWMp8cwmb_-vw2M',
    appId: '1:487529716430:ios:83a9957c8183b1f41d8e9f',
    messagingSenderId: '487529716430',
    projectId: 'barrelsnap-8b4a6',
    storageBucket: 'barrelsnap-8b4a6.appspot.com',
    iosBundleId: 'com.example.barrelsnap01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4XzQ8Hud8eFnSjIvJDWMp8cwmb_-vw2M',
    appId: '1:487529716430:ios:42fb5b9e100314cc1d8e9f',
    messagingSenderId: '487529716430',
    projectId: 'barrelsnap-8b4a6',
    storageBucket: 'barrelsnap-8b4a6.appspot.com',
    iosBundleId: 'com.example.barrelsnap01.RunnerTests',
  );
}