@startuml BarrelSnap_StateMachineDiagram

[*] --> NotRegistered
NotRegistered --> Registered: Register
Registered --> LoggedIn: Login
LoggedIn --> ClientHomePage: Role: Client
LoggedIn --> ManagerHomePage: Role: Manager
ClientHomePage --> BuyWines: Buy Wines
ClientHomePage --> FollowNewsletter: Follow Wine Newsletter
ManagerHomePage --> ManageWinery: Manage Winery
ManagerHomePage --> SellWines: Sell Wines
ManagerHomePage --> AddWines: Add Wines for Sell
BuyWines --> ClientHomePage: Return
FollowNewsletter --> ClientHomePage: Return
ManageWinery --> ManagerHomePage: Return
SellWines --> ManagerHomePage: Return
AddWines --> ManagerHomePage: Return
LoggedIn --> [*]: Logout

@enduml
